<!-- 
작성자 : 이호연
페이지 설명 : 경로 보여주기
 -->
 <!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<link href='https://fonts.googleapis.com/css?family=Hind' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="static/css/style.css">
	<link rel="stylesheet" type="text/css" href="static/css/dialog.css">
	<link rel="stylesheet" type="text/css" href="static/css/path.css">
</head>
<body>
	<!-- 경로 목록 -->
	<section class="dialog path">
		<section class="dialog_head">
			<a href="#"><img src="icon/edit_black.png"></a>
		</section>
		<section class="dialog_body">
			<article class="dialog_article path_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p class = "time">2h</p>
			</article>
			<article class="dialog_article path_info">
				<img src="static/image/walk.png">
				<p>
					Lorem ipsum dolor sit arnet, ee cctur consectetur ad...
				</p>
			</article>
			<article class="dialog_article path_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p class = "time">2h</p>
			</article>
			<article class="dialog_article path_info">
				<img src="static/image/walk.png">
				<p>
					Lorem ipsum dolor sit arnet, ee cctur consectetur ad...
				</p>
			</article>
			<article class="dialog_article path_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p class = "time">2h</p>
			</article>
			<article class="dialog_article path_info">
				<img src="static/image/walk.png">
				<p>
					Lorem ipsum dolor sit arnet, ee cctur consectetur ad...
				</p>
			</article>
		</section>
	</section>
</body>
</html>