<!-- 
작성자 : 이호연
페이지 설명 : 관광지 목록 리스트
필요한 css : dialog.css, tourlist.css
-->
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<link href='https://fonts.googleapis.com/css?family=Hind' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="static/css/style.css">
	<link rel="stylesheet" type="text/css" href="static/css/dialog.css">
	<link rel="stylesheet" type="text/css" href="static/css/tourlist.css">
</head>
<body>
	<!-- 관광지 목록 -->
	<section class="dialog tourList">
		<section class="dialog_head">
			<a href="#"><img src="static/image/all_grey.png"></a>
			<a href="#"><img src="static/image/culture_grey.png"></a>
			<a href="#"><img src="static/image/nature_grey.png"></a>
			<a href="#"><img src="static/image/trend_grey.png"></a>
			<a href="#"><img src="static/image/shopping_grey.png"></a>
			<a class="search" href="#"><img src="static/image/search_grey.png"></a>
		</section>
		<section class="dialog_body">
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
			<article class="dialog_article">
				<img src="static/image/sampleImage.jpg">
				<h1>Gyeongbokgung</h1>
				<p>
					Lorem ipsum dolor sit arnet, consectur consectetur ad...
				</p>
			</article>
		</section>
	</section>
</body>
</html>