<!-- 
작성자 : 이호연
페이지 설명 : 경로 보여주기
필요한 css : dialog.css, path.css
 -->
<!-- 경로 목록 -->
<section class="dialog path">
	<section class="dialog_head">
		<a href="#">edit</a>
	</section>
	<section class="dialog_body">
		<article class="dialog_article path_article">
			<img src="/static/image/sampleImage.jpg">
			<h1>Gyeongbokgung</h1>
			<p class = "time">2h</p>
		</article>
		<article class="dialog_article path_info">
			<img src="/static/image/walk.png">
			<p>
				Lorem ipsum dolor sit arnet, ee cctur consectetur ad...
			</p>
		</article>
		<article class="dialog_article path_article">
			<img src="/static/image/sampleImage.jpg">
			<h1>Gyeongbokgung</h1>
			<p class = "time">2h</p>
		</article>
		<article class="dialog_article path_info">
			<img src="/static/image/walk.png">
			<p>
				Lorem ipsum dolor sit arnet, ee cctur consectetur ad...
			</p>
		</article>
		<article class="dialog_article path_article">
			<img src="/static/image/sampleImage.jpg">
			<h1>Gyeongbokgung</h1>
			<p class = "time">2h</p>
		</article>
		<article class="dialog_article path_info">
			<img src="/static/image/walk.png">
			<p>
				Lorem ipsum dolor sit arnet, ee cctur consectetur ad...
			</p>
		</article>
	</section>
	<section class="dialog_foot">
		<a class="click">list</a>
		<a>map</a>
	</section>
</section>